=== Global-Solutions/gsolIcalUtil/src/main/schema/gsol-ical-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://global-solutions.co.jp/ical/config/general"
    elementFormDefault="qualified"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://global-solutions.co.jp/ical/config/general"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
    jaxb:version="2.0">
    <annotation>
        <appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="jp.co.gsol.oss.ical.config.general"/>
            </jaxb:schemaBindings>
        </appinfo>
    </annotation>
    <element name="gsol-ical-config">
        <complexType>
            <all>
                <element name="document-directry" minOccurs="1" maxOccurs="1" type="string"/>
                <element name="location-path" minOccurs="1" maxOccurs="1" type="string"/>
                <element name="prod-id" minOccurs="1" maxOccurs="1" type="string"/>
                <element name="calendar-name-template" minOccurs="1" maxOccurs="1" type="string"/>
                <element name="auto-mkdir" type="boolean" minOccurs="0" maxOccurs="1" />
                <element name="auto-recovery-file" type="boolean" minOccurs="0" maxOccurs="1"/>
                <element name="ics-start-month" type="tns:negative-integer" minOccurs="0" maxOccurs="1"/>
                <element name="ics-end-month" type="tns:positive-integer" minOccurs="0" maxOccurs="1"/>
                <element name="ics-filename-len" type="tns:positive-integer" minOccurs="0" maxOccurs="1"/>
                <element name="ics-file-extension" type="string" minOccurs="0" maxOccurs="1"/>
                <element name="temp-file-prefix" type="string" minOccurs="0" maxOccurs="1"/>
                <element name="temp-file-suffix" type="string" minOccurs="0" maxOccurs="1"/>
                <element name="charset" type="string" minOccurs="0" maxOccurs="1"/>
                <element name="iac-sch-event-date-pattern" type="string" minOccurs="0" maxOccurs="1"/>
            </all>
        </complexType>
    </element>
    <simpleType name="positive-integer">
        <restriction base="integer">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>
    <simpleType name="negative-integer">
        <restriction base="integer">
            <maxInclusive value="0"/>
        </restriction>
    </simpleType>
</schema>

=== Global-Solutions/gsolIcalUtil/src/main/conf/gsol-ical-config/gsol-ical-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<gsol-ical-config
    xmlns="http://global-solutions.co.jp/ical/config/general"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://global-solutions.co.jp/ical/config/general ../schema/gsol-ical-config.xsd ">

    <document-directry>\absolute\path\to\your\webapp\ical\ics</document-directry>
    <location-path>http://example.com/ical/ics</location-path>
    <prod-id>"-//Global Solutions Co., Ltd.//iAC Calendar/EN"</prod-id>
    <calendar-name-template>{userCd} @ iAC Calendar</calendar-name-template>
    <auto-mkdir>true</auto-mkdir>
    <auto-recovery-file>false</auto-recovery-file>
    <ics-start-month>-1</ics-start-month>
    <ics-end-month>13</ics-end-month>
</gsol-ical-config>
